dist: xenial
language: scala
jdk: openjdk8
matrix:
  include:
  - script:
    - sbt "project rootJVM"
      update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
  - script:
    - sbt "project rootJVM" "set ThisBuild / usePipelining := true" "show usePipelining"
      update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
      clean update compile
