name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 6 * * 3'
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: jvm-js
          - name: scala-native
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v6
    - run: git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
    - run: git show --oneline --check
    - run: |
        case ${{ matrix.name }} in
          "jvm-js")
            sbt -v \
            -sbt-opts .github/workflows/.sbtopts \
            scalafmtCheckAll \
            scalafmtSbtCheck \
            checkGenerateCodeError \
            "+ Test/compile" \
            "+ scalapropsTestNames" \
            "+ scalapropsJS/test" \
            "+ scalapropsJVM/test" \
            "+ scalazJS/test" \
            "+ scalazJVM/test" \
            "project /" \
            "+ publishLocal"
            ;;
          "scala-native")
            sbt -v \
            -sbt-opts .github/workflows/.sbtopts \
            "+ rootNative/Test/nativeLink" \
            "+ scalapropsNative/test" \
            "+ scalazNative/test"
            ;;
          *)
            echo "unknown job-name"
            exit 1
        esac
    - run: rm -rf "$HOME/.ivy2/local"
